# Generated by Django 4.0 on 2022-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('text', models.CharField(max_length=300, verbose_name='Текст Статьи')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
