# Generated by Django 4.0 on 2022-02-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='data',
        ),
    ]
